/* extractngram_cmdline.h */

/* File autogenerated by gengetopt version 2.10  */

#ifndef EXTRACTNGRAM_CMDLINE_H
#define EXTRACTNGRAM_CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "extractngram"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION ""
#endif

struct gengetopt_args_info
{
  char * to_arg;	/* output stream encoding (for character ngram only) (default='UTF-8').  */
  char * input_arg;	/* ngram file name,not including .ngram.  */
  int min_n_arg;	/* extract N gram (where N >= n).  */
  int max_n_arg;	/* extract N gram (N <= m) (max M=255,M=N if omitted).  */
  int freq_arg;	/* extract N gram whose freq >= f (default='1').  */
  int mmap_flag;	/* use mmap() for faster operation (default=off).  */
  int count_flag;	/* only count the number of N-gram extracted (default=off).  */
  int char_flag;	/* extract char ngram (default=off).  */
  int nopunct_flag;	/* exclude N gram with (CJK) punctuations and special symbols (non-word) (default=off).  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int to_given ;	/* Whether to was given.  */
  int input_given ;	/* Whether input was given.  */
  int min_n_given ;	/* Whether min-n was given.  */
  int max_n_given ;	/* Whether max-n was given.  */
  int freq_given ;	/* Whether freq was given.  */
  int mmap_given ;	/* Whether mmap was given.  */
  int count_given ;	/* Whether count was given.  */
  int char_given ;	/* Whether char was given.  */
  int nopunct_given ;	/* Whether nopunct was given.  */

  char **inputs ; /* unamed options */
  unsigned inputs_num ; /* unamed options number */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* EXTRACTNGRAM_CMDLINE_H */
