/* text2ngram_cmdline.h */

/* File autogenerated by gengetopt version 2.10  */

#ifndef TEXT2NGRAM_CMDLINE_H
#define TEXT2NGRAM_CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "text2ngram"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION ""
#endif

struct gengetopt_args_info
{
  char * from_arg;	/* input stream encoding (for character ngram only) (default='UTF-8').  */
  char * to_arg;	/* output stream encoding (for character ngram only) (default='UTF-8').  */
  char * output_arg;	/* ngram file name.  */
  int mem_arg;	/* size of memory(MB) to use (default='50').  */
  int char_flag;	/* counting char ngram (default=off).  */
  int mmap_flag;	/* use mmap() for disk merging (default=off).  */
  int min_n_arg;	/* extract N gram (where N >= n).  */
  int max_n_arg;	/* extract N gram (N <= m) (max M=255,M=N if omitted).  */
  int freq_arg;	/* extract N gram whose freq >= f (default='1').  */
  int nopunct_flag;	/* exclude N gram with punctuations and special symbols (non-word) (default=off).  */
  int wordlen_arg;	/* average word length when count word ngrams.this option is a hint for pre-allocate memory (default='3').  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int from_given ;	/* Whether from was given.  */
  int to_given ;	/* Whether to was given.  */
  int output_given ;	/* Whether output was given.  */
  int mem_given ;	/* Whether mem was given.  */
  int char_given ;	/* Whether char was given.  */
  int mmap_given ;	/* Whether mmap was given.  */
  int min_n_given ;	/* Whether min-n was given.  */
  int max_n_given ;	/* Whether max-n was given.  */
  int freq_given ;	/* Whether freq was given.  */
  int nopunct_given ;	/* Whether nopunct was given.  */
  int wordlen_given ;	/* Whether wordlen was given.  */

  char **inputs ; /* unamed options */
  unsigned inputs_num ; /* unamed options number */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TEXT2NGRAM_CMDLINE_H */
